### Multi stage docker

### Build Angular app
FROM node:current-alpine as node
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --prod

### Deploy nginx
FROM nginx:alpine
MAINTAINER Cheng Zou & Kyle Zeeuwen

RUN apk add --update \
    "vim" \
    "jq" \
    "curl" \
    "bash" \
  && rm -rf /var/cache/apk/*
RUN mkdir -p /var/share/log

ADD ./nginx.template /etc/nginx/
RUN rm -rf /usr/share/nginx/html/*
COPY --from=node /app/dist/angular /usr/share/nginx/html

ENV TEMPLATE=nginx.template
EXPOSE 80 443

CMD ["/bin/bash", "-c", "envsubst '$$HOSTNAME' < /etc/nginx/$TEMPLATE > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]